### ISSUE TITLE
Feedback on 2.3.2 - keeping the pipe full 

### ISSUE THREAD

**Issue by oesh** [SystemsApproach/tcpcc#16]
Paragraph 2.3.2 introduces the reader to the `delay x bandwidth product` concept.
This concept is often abbreviated to `BDP`, i.e, `bandwidth x delay product`.

Perhaps, it would make sense to:
a. Mention the `BDP` abbreviation in 2.3.2; and
b. use `bandwidth x delay product` instead of `delay x bandwidth product`.

**Comment by drbruced12** [comment]
We actually were never consistent, and used 3 or 4 different forms of this term. I have proposed a fix to consistently use the more common "bandwidth-delay product". I don't feel another acronym is necessary. Thanks for the feedback.

**Comment by llpeterson** [comment]
Changes have been merged.
