### ISSUE TITLE
Feedback on 7.3 - HTTP Performance (QUIC)

### ISSUE THREAD

**Issue by oesh** [SystemsApproach/tcpcc#17]
7.3 mentions "there's a lot more we can cover here", but maybe it would be appropriate to mention that despite QUIC origins in HTTP, it has evolved into other application protocols. For example, streaming video (https://www.ietf.org/id/draft-kpugin-rush-01.html) or tunneling traffic (https://developer.apple.com/support/prepare-your-network-for-icloud-private-relay). Maybe it's worth mentioning.

Another relevant note on QUIC: since the QUIC stack resides in the application memory space, applications can experiment with different CCAs even more freely.  For example, Meta reported use of QUIC + Copa for video streaming: https://engineering.fb.com/2019/11/17/video-engineering/copa/ .

**Comment by drbruced12** [comment]
I've added a comment about non-HTTP uses of QUIC in commit https://github.com/SystemsApproach/tcpcc/commit/baa481d625b8bcee6b59e5f5fd2f7df93be438d6

The point about multiple CCAs was already made in Section 7.3.

Thanks for the feedback!
