### ISSUE TITLE
Feedback on 7.4 - DASH

### ISSUE THREAD

**Issue by oesh** [SystemsApproach/tcpcc#21]
Section 7.4 mentions that 
> One of the key realizations that made DASH feasible was the idea that one could encode video at multiple quality levels with different bandwidth requirements, and store them all in advance on a streaming server. Then, as soon as the observed throughput of the network drops, the server can drop to a lower quality stream, and then ramp up to higher quality as conditions permit.  

Perhaps it's worth mentioning that DASH makes it extremely easy to leverage CDNs, so that the multiple quality levels can be served from the edge location vs. from the data center. Shortening the network path reduces the feedback propagation time, and the edge location can react faster to sudden changes in goodput. As a result, the watcher experience improves.

**Comment by drbruced12** [comment]
Agreed, I will add this.

**Comment by drbruced12** [comment]
https://github.com/SystemsApproach/tcpcc/commit/ad9d614043a33437afa8c560d6a21e6a9bf02ab3
