### ISSUE TITLE
Feedback on 7.5 - Multipath

### ISSUE THREAD

**Issue by oesh** [SystemsApproach/tcpcc#22]
Maybe its worth mentioning the MP-QUIC effort, which had been recently re-focused:

https://datatracker.ietf.org/doc/draft-lmbdhk-quic-multipath/

**Comment by drbruced12** [comment]
I don't like referencing Internet drafts, especially those which are not yet WG products, as they present a moving target, but the idea that Multipath CC could be applied to QUIC is probably worth a mention (as the authors of RFC 6356 mention the independence from TCP).

**Comment by drbruced12** [comment]
Closed with commit https://github.com/SystemsApproach/tcpcc/commit/ad9d614043a33437afa8c560d6a21e6a9bf02ab3

**Comment by drbruced12** [comment]
https://github.com/SystemsApproach/tcpcc/commit/ad9d614043a33437afa8c560d6a21e6a9bf02ab3
