### ISSUE TITLE
Feedback on 7.6 - Mobile Cellular Networks

### ISSUE THREAD

**Issue by oesh** [SystemsApproach/tcpcc#24]
> 1) the wireless link is typically the bottleneck due to the scarcity of radio spectrum, and (2) the bandwidth available in the RAN can be highly variable due to a combination of device mobility and radio interference. 

Maybe it's worth clarifying that the user mobility leads to variations in both the availability of and the demand for bandwidth. For example, consider two high-speed trains moving in opposite directions.  As the two meet, the nearest cell tower will experience double demand. 

On the same note, maybe it's worth mentioning TCP Prague in the context of mobile-cellular networks.

**Comment by llpeterson** [comment]
I'll work to clarify the explanation of why the RAN is problematic. Thanks for the suggestion.

With respect to TCP Prague, you likely understand it better than me, but I'm not sure what unique insights it gives us into the mobile network use case. (My understanding is that Prague is trying to be general-purpose, and that's one of many scenarios in which its been evaluated.) Is there a particular citation you have in mind?

**Comment by llpeterson** [comment]
I tracked down a couple citations and added them to the annotated bibliography. We'll track progress with Prague and decide somewhere down the line whether to promote it to the main body of the book.
