### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by deepakpjose** [SystemsApproach/tcpcc#32]
Unable to create a pull request. Hence giving the diff's for typos here as an issue.

Author: deepakjo <deepakpjose@gmail.com>
Date:   Thu May 26 18:26:04 2022 +0530

    minor changes

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
modified: intro.rst
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
@ intro.rst:404 @ subsequent chapters, but you can rest assured that new ideas in
congestion control will continue to emerge for years to come.

Sometimes innovations are necessitated by changes in the
landscape. For example, as bandwidths increased from megabits to
landscape. For example, as bandwidth increased from megabits to <--bandwidth instead of bandwidths.
gigabits per second, the amount of data in flight at any instant
increased, which raises the stakes for detecting and responding to
congestion quickly.  High latency links, such as trans-oceanic cables
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
modified: tcp_ip.rst
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
@ tcp_ip.rst:71 @ addressed by routing.  While it is true that a congested link could be
assigned a large "cost" by a routing protocol, in an effort to make
traffic avoid that link, this can't solve the overall problem of too
much traffic being offered to a bottleneck link. To see this, we need
look no further than the simple network depicted in :numref:`Figure %s
to look no further than the simple network depicted in :numref:`Figure %s <--- we need to look no further
<fig-congestion>`, where all traffic has to flow through the same
router to reach the destination. Although this is an extreme example,
it is common to have at least one link that it is not possible to

**Comment by drbruced12** [comment]
Thanks for these suggestions. I view them as matters of taste rather than correctness - both sentences read correctly as written. So I'm going to close this issue.
