### ISSUE TITLE
1 Introduction (first para)

### ISSUE THREAD

**Issue by goelvidhi** [SystemsApproach/tcpcc#33]
There is a text that says “… tens of bits per day…”

Was it intended to be tens of trillion bits per day?

**Comment by drbruced12** [comment]
No, this is correct. The full context is "The Internet...accommodates
transmission rates ranging from tens of bits per day to hundreds of
gigabits per second.". That is, it can deal with very low speeds (e.g. IoT devices that send almost nothing) to very high speeds (e.g. the Internet backbone).
