### ISSUE TITLE
Typo in 1.2 Controlling congestion

### ISSUE THREAD

**Issue by goelvidhi** [SystemsApproach/tcpcc#34]
“…and dropped arriving packets if they…”

s/they/the

**Comment by drbruced12** [comment]
I feel like you must be looking at a cached copy of the book. This was resolved in commit 80e16cde485. Can you provide a link to your source for this typo?

**Comment by goelvidhi** [comment]
Thank you for double checking, I wrote my comment a couple month ago. Sorry for posting them so late.
