### ISSUE TITLE
4.2 Additive Increase/Multiplicative Decrease

### ISSUE THREAD

**Issue by goelvidhi** [SystemsApproach/tcpcc#40]
A. Sentence reads incorrectly, probably doesn’t need this sender,
`The central challenge is computing an estimate of how much traffic the network this sender can safely transmit.`

B. This isn’t true for today’s stacks as samples are taken every ACK

`2)due to the cost of measuring each transmission with an accurate clock, TCP only samples the round-trip time once per RTT (rather than once per packet) using a coarse-grained (500-ms) clock.`

**Comment by drbruced12** [comment]
Thanks, we've made changes to address both these points.
